# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.srcs/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0.xci
# IP: The module: 'system_axi_gpio_5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_5_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.srcs/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0.xci
# IP: The module: 'system_axi_gpio_5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/RP/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_5_0/system_axi_gpio_5_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
