# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2.xci
# IP: The module: 'system_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.srcs/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2.xci
# IP: The module: 'system_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_rst_ps7_0_50M_2/system_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
