# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/cfg/clocks.xdc

# XDC: C:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_0_0/system_signal_split_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_0_0 || ORIG_REF_NAME==system_signal_split_2_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/system/ip/system_Trigger_0_0/system_Trigger_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Trigger_0_0 || ORIG_REF_NAME==system_Trigger_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_2_1/system_axi_gpio_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_1 || ORIG_REF_NAME==system_axi_gpio_2_1} -quiet] -quiet

# IP: bd/system/ip/system_scale_0_0/system_scale_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_scale_0_0 || ORIG_REF_NAME==system_scale_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_7_0/system_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_7_0 || ORIG_REF_NAME==system_axi_gpio_7_0} -quiet] -quiet

# IP: bd/system/ip/system_Selector_1_0/system_Selector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Selector_1_0 || ORIG_REF_NAME==system_Selector_1_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_2_0_1/system_signal_split_2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_2_0_1 || ORIG_REF_NAME==system_signal_split_2_0_1} -quiet] -quiet

# IP: bd/system/ip/system_PID_C_0_0/system_PID_C_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PID_C_0_0 || ORIG_REF_NAME==system_PID_C_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_4 || ORIG_REF_NAME==system_axi_gpio_0_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_5 || ORIG_REF_NAME==system_axi_gpio_0_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_2_3/system_axi_gpio_2_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_3 || ORIG_REF_NAME==system_axi_gpio_2_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_2_4/system_axi_gpio_2_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_4 || ORIG_REF_NAME==system_axi_gpio_2_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_5 || ORIG_REF_NAME==system_axi_gpio_2_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_2_6/system_axi_gpio_2_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_6 || ORIG_REF_NAME==system_axi_gpio_2_6} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_2/system_processing_system7_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_2 || ORIG_REF_NAME==system_processing_system7_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xbar_3/system_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_3 || ORIG_REF_NAME==system_xbar_3} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_4/system_ps7_0_axi_periph_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_4 || ORIG_REF_NAME==system_ps7_0_axi_periph_4} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_9_0/system_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_9_0 || ORIG_REF_NAME==system_axi_gpio_9_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_9_1/system_axi_gpio_9_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_9_1 || ORIG_REF_NAME==system_axi_gpio_9_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_10_0/system_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_10_0 || ORIG_REF_NAME==system_axi_gpio_10_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/system_ooc.xdc
