# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.srcs/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5.xci
# IP: The module: 'system_axi_gpio_2_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.srcs/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5.xci
# IP: The module: 'system_axi_gpio_2_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/Project_folder/Vivado/Red-Pitaya-main/Complete_setup/tmp/PID_Ben_Final/PID_Ben_Final.gen/sources_1/bd/system/ip/system_axi_gpio_2_5/system_axi_gpio_2_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
