# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.srcs/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4.xci
# IP: The module: 'system_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.srcs/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4.xci
# IP: The module: 'system_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/benja/Desktop/clean/tmp/WIP3/WIP3.gen/sources_1/bd/system/ip/system_axi_gpio_0_4/system_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
